spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/apiprova
    username: admin
    password: Patrick1997
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false